version: '3.8'

services:
  web:
    image: zackcpetersen/portfolio_backend:latest
    build:
      context: ../../  # root of current project - context for Dockerfile
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ../../:/usr/src/app
    ports:
      - '8000:8000'
    env_file:
      - ./dev.env
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    volumes:
       - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio

volumes:
  postgres-data:
