# Generated by Django 3.2.6 on 2022-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
