# Generated by Django 3.2.6 on 2022-03-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projecttag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdescription',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='projectdescription',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='projectdescription',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='Project/Title Unique'),
        ),
        migrations.AddConstraint(
            model_name='projectdescription',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='Project/Order Unique'),
        ),
    ]
