# Generated by Django 3.2.6 on 2022-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220305_1853'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projecttag',
            constraint=models.UniqueConstraint(fields=('project', 'tag'), name='Project Tag Unique'),
        ),
    ]
