# Generated by Django 3.2.6 on 2022-03-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projecttag_project tag unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
