# Generated by Django 4.0.3 on 2022-03-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='hello', max_length=999999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='hello', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectDescription',
        ),
    ]
