version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
#    image: portfolio_prod_nginx
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
       - postgres-data:/var/lib/postgresql/data/
#    ports:
#      - '5432:5432'
    expose:
      - 5432
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio

volumes:
  postgres-data: