# Generated by Django 4.0.3 on 2022-03-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='title',
            new_name='name',
        ),
    ]
