version: '3.8'

services:
  web:
#    image: zackcpetersen/portfolio_backend:latest
    build:
      context: ../../  # root of current project - context for Dockerfile
      dockerfile: ./docker/prod/Dockerfile
#    volumes:
#      - ../../:/usr/src/app
    expose:
      - 8000
    ports:
      - '8000:8000'
    env_file:
      - ./prod.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio

  nginx:
#    image: zackcpetersen/portfolio_nginx:latest
    build:
      context: ../../
      dockerfile: ./docker/prod/nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - web

volumes:
  postgres_data:
